//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkinKececiBlogSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EkinKececiBlogSite.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        public static string Adınız {
            get {
                return ResourceManager.GetString("Adınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız Soyadınız.
        /// </summary>
        public static string Adınız_Soyadınız {
            get {
                return ResourceManager.GetString("Adınız Soyadınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Bilgileri.
        /// </summary>
        public static string Adres_Bilgileri {
            get {
                return ResourceManager.GetString("Adres Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benimle İletişime Geçin.
        /// </summary>
        public static string Benimle_İletişime_Geçin {
            get {
                return ResourceManager.GetString("Benimle İletişime Geçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogları yakından takip edin.
        /// </summary>
        public static string Blogları_yakından_takip_edin {
            get {
                return ResourceManager.GetString("Blogları yakından takip edin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloglarım.
        /// </summary>
        public static string Bloglarım {
            get {
                return ResourceManager.GetString("Bloglarım", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string Detaylar {
            get {
                return ResourceManager.GetString("Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detayları Gör.
        /// </summary>
        public static string Detayları_Gör {
            get {
                return ResourceManager.GetString("Detayları Gör", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamını Gör.
        /// </summary>
        public static string Devamını_Gör {
            get {
                return ResourceManager.GetString("Devamını Gör", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamını Oku.
        /// </summary>
        public static string Devamını_Oku {
            get {
                return ResourceManager.GetString("Devamını Oku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÖNDER.
        /// </summary>
        public static string GÖNDER {
            get {
                return ResourceManager.GetString("GÖNDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımda.
        /// </summary>
        public static string Hakkımda {
            get {
                return ResourceManager.GetString("Hakkımda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkımızda {
            get {
                return ResourceManager.GetString("Hakkımızda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ı.
        /// </summary>
        public static string ı {
            get {
                return ResourceManager.GetString("ı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string İletişim {
            get {
                return ResourceManager.GetString("İletişim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        public static string İletişim_Bilgileri {
            get {
                return ResourceManager.GetString("İletişim Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string Kategori {
            get {
                return ResourceManager.GetString("Kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Kategoriler {
            get {
                return ResourceManager.GetString("Kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresiniz.
        /// </summary>
        public static string Mail_Adresiniz {
            get {
                return ResourceManager.GetString("Mail Adresiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü.
        /// </summary>
        public static string Menü {
            get {
                return ResourceManager.GetString("Menü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Konusu.
        /// </summary>
        public static string Mesaj_Konusu {
            get {
                return ResourceManager.GetString("Mesaj Konusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız.
        /// </summary>
        public static string Mesajınız {
            get {
                return ResourceManager.GetString("Mesajınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeler.
        /// </summary>
        public static string Projeler {
            get {
                return ResourceManager.GetString("Projeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Linkleri.
        /// </summary>
        public static string Site_Linkleri {
            get {
                return ResourceManager.GetString("Site Linkleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Blog Kayıtları.
        /// </summary>
        public static string Son_Blog_Kayıtları {
            get {
                return ResourceManager.GetString("Son Blog Kayıtları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Ağlar.
        /// </summary>
        public static string Sosyal_Ağlar {
            get {
                return ResourceManager.GetString("Sosyal Ağlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya.
        /// </summary>
        public static string Sosyal_Medya {
            get {
                return ResourceManager.GetString("Sosyal Medya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip Edin.
        /// </summary>
        public static string Takip_Edin {
            get {
                return ResourceManager.GetString("Takip Edin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YORUM YAP.
        /// </summary>
        public static string YORUM_YAP {
            get {
                return ResourceManager.GetString("YORUM YAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        public static string Yorumlar {
            get {
                return ResourceManager.GetString("Yorumlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumunuz.
        /// </summary>
        public static string Yorumunuz {
            get {
                return ResourceManager.GetString("Yorumunuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumunuzu Bırakın.
        /// </summary>
        public static string Yorumunuzu_Bırakın {
            get {
                return ResourceManager.GetString("Yorumunuzu Bırakın", resourceCulture);
            }
        }
    }
}
